// src/utils/facts.ts
// Typed access to the generated facts dataset (data/facts.json).
// The file is regenerated by scripts/fetch-facts.mjs + generate-vaapen-context.mjs;
// until those have run it is an empty placeholder, so callers must handle null.

import type { KommuneFacts, KommuneFactsFile } from "../types/facts";
import rawFacts from "../../data/facts.json";

const factsFile = rawFacts as unknown as KommuneFactsFile;

export function getKommuneFacts(kommunenummer: string): KommuneFacts | null {
    return factsFile.kommuner[kommunenummer] ?? null;
}

/** True if the generated dataset is present (not just the placeholder). */
export function hasFactsData(): boolean {
    return Object.keys(factsFile.kommuner).length > 0;
}
